spring:
  datasource:
    url: jdbc:postgresql://localhost:4000/flexisafsecurity
    username: postgres
    password: 2326
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
